name: Run Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npx http-server . -p 8080
          wait-on: 'http://localhost:8080'
          browser: chrome
